version: '3'
services:
    springboot:
        container_name: springboot-minikube
        image: dokkl/springboot-minikube:1.0
        ports: 
        - 9090:8080
    mysql:
        container_name: mysql
        image: mysql:5.7
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
        - MYSQL_DATABASE=demo
        volumes:
        - appvolume:/var/lib/mysql
volumes:
    appvolume:  
